# 工作流名称
name: Build SharpRDP Project

# 工作流触发条件
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 新增步骤：安装 .NET Framework 4.5.2 Developer Pack
      # 这是解决 MSB3644 错误的关键步骤
      - name: Install .NET Framework 4.5.2 Developer Pack
        run: |
          # 使用 PowerShell 下载开发者工具包的安装程序
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901954-DevPack-ENU.exe" -OutFile "dotnet-devpack.exe"
          # 以静默和非重启模式执行安装程序。'/q' 表示安静模式，'/norestart' 表示安装后不自动重启
          Start-Process -FilePath ".\dotnet-devpack.exe" -ArgumentList "/q /norestart" -Wait
        shell: powershell

      # 第三步：设置 MSBuild 环境
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 第四步：恢复 NuGet 包
      - name: Restore NuGet packages
        run: nuget restore SharpRDP/SharpRDP.sln

      # 第五步：编译解决方案
      - name: Build the solution
        run: msbuild SharpRDP/SharpRDP.sln /p:Configuration=Release

      # 第六步：上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SharpRDP-Release-Build
          path: SharpRDP/bin/Release/
