# 工作流名称
name: Build SharpRDP Project

# 工作流触发条件
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 更新步骤：安装 .NET Framework 4.5.2 Developer Pack (使用新的有效链接)
      - name: Install .NET Framework 4.5.2 Developer Pack
        run: |
          # 定义下载链接和输出文件名
          $url = "https://web.archive.org/web/20210506182231/https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901954-DevPack-ENU.exe"
          $outputFile = "dotnet-devpack.exe"
          
          # 下载文件
          Write-Host "Downloading .NET Framework 4.5.2 Developer Pack..."
          Invoke-WebRequest -Uri $url -OutFile $outputFile
          
          # 检查文件是否成功下载
          if (-not (Test-Path $outputFile)) {
              Write-Error "Failed to download the developer pack."
              exit 1
          }
          
          # 以静默和非重启模式执行安装程序
          Write-Host "Installing developer pack..."
          Start-Process -FilePath ".\$outputFile" -ArgumentList "/q /norestart" -Wait
          Write-Host "Installation complete."
        shell: powershell

      # 第三步：设置 MSBuild 环境
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 第四步：恢复 NuGet 包
      - name: Restore NuGet packages
        run: nuget restore SharpRDP/SharpRDP.sln

      # 第五步：编译解决方案
      - name: Build the solution
        run: msbuild SharpRDP/SharpRDP.sln /p:Configuration=Release

      # 第六步：上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SharpRDP-Release-Build
          path: SharpRDP/bin/Release/
