name: Build SharpRDP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Install .NET Framework 4.5 Developer Pack
      shell: powershell
      run: |
        Write-Host "Downloading .NET Framework 4.5 Developer Pack directly..."
        
        # Direct download link for .NET Framework 4.5 Developer Pack
        $url = "https://download.microsoft.com/download/7/0/2/702D830A-9D94-4241-912B-D39BEF672E76/NDP45-KB2505728-x86-x64-DevPack.exe"
        $outpath = "$env:TEMP\NDP45-DevPack.exe"
        
        Write-Host "Downloading from: $url"
        (New-Object System.Net.WebClient).DownloadFile($url, $outpath)
        
        Write-Host "Installing .NET Framework 4.5 Developer Pack..."
        # Silent install flags
        Start-Process -FilePath $outpath -ArgumentList "/quiet /norestart" -Wait -NoNewWindow
        
        Write-Host ".NET Framework 4.5 Developer Pack installation completed"
        
        # Verify installation
        if (Test-Path "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5") {
            Write-Host ".NET Framework 4.5 Reference Assemblies verified successfully"
            Get-ChildItem "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" | Select-Object Name -First 5
        } else {
            Write-Error "Reference Assemblies directory not found at expected location"
            # List available .NET Framework versions for troubleshooting
            Write-Host "Available .NET Framework versions:"
            Get-ChildItem "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework" -ErrorAction SilentlyContinue | Select-Object Name
        }
      
    - name: Restore NuGet packages
      run: |
        cd SharpRDP
        nuget restore SharpRDP.sln
      
    - name: Build Solution
      run: |
        cd SharpRDP
        msbuild SharpRDP.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Compress DLLs
      shell: powershell
      run: |
        # Import necessary namespace for compression
        Add-Type -AssemblyName System.IO.Compression
        
        # Function to compress file using Deflate
        function Compress-FileDeflate {
            param (
                [string]$SourceFile,
                [string]$DestinationFile
            )
            
            try {
                $input = [System.IO.File]::OpenRead($SourceFile)
                $output = [System.IO.File]::Create($DestinationFile)
                $compressor = New-Object System.IO.Compression.DeflateStream($output, [System.IO.Compression.CompressionMode]::Compress)
                
                $input.CopyTo($compressor)
                
                $compressor.Close()
                $output.Close()
                $input.Close()
                
                Write-Host "Successfully compressed $SourceFile to $DestinationFile"
            }
            catch {
                Write-Host "Error compressing file: $_"
            }
        }
        
        # Compress the DLLs with Deflate if they exist
        $binDir = ".\SharpRDP\SharpRDP\bin\Release"
        if (Test-Path "$binDir\AxInterop.MSTSCLib.dll") {
            Compress-FileDeflate -SourceFile "$binDir\AxInterop.MSTSCLib.dll" -DestinationFile "$binDir\AxInterop.MSTSCLib.dll.bin"
        } else {
            Write-Host "Warning: AxInterop.MSTSCLib.dll not found"
        }
        
        if (Test-Path "$binDir\Interop.MSTSCLib.dll") {
            Compress-FileDeflate -SourceFile "$binDir\Interop.MSTSCLib.dll" -DestinationFile "$binDir\Interop.MSTSCLib.dll.bin"
        } else {
            Write-Host "Warning: Interop.MSTSCLib.dll not found"
        }
      
    - name: List output files
      shell: pwsh
      run: |
        Get-ChildItem -Path .\SharpRDP\SharpRDP\bin\Release\ -Recurse | Select-Object FullName, Length
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SharpRDP-Release
        path: |
          SharpRDP/SharpRDP/bin/Release/SharpRDP.exe
          SharpRDP/SharpRDP/bin/Release/*.dll.bin
        retention-days: 30
        if-no-files-found: error
        compression-level: 6
        overwrite: true

    - name: Create Release Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path .\release-package
        Copy-Item .\SharpRDP\SharpRDP\bin\Release\SharpRDP.exe .\release-package\
        Copy-Item .\SharpRDP\SharpRDP\bin\Release\*.dll.bin .\release-package\
        Compress-Archive -Path .\release-package\* -DestinationPath .\SharpRDP-release.zip -Force
    
    - name: Upload Release Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: SharpRDP-Release-Package
        path: SharpRDP-release.zip
        retention-days: 30
