name: Build SharpRDP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore NuGet packages
      run: nuget restore SharpRDP.sln
      
    - name: Build Solution
      run: msbuild SharpRDP.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Compress DLLs
      shell: powershell
      run: |
        # Create required directory if not exists
        New-Item -ItemType Directory -Force -Path ".\SharpRDP\bin\Release" | Out-Null
        
        # Compress the DLLs with Deflate if they exist
        if (Test-Path ".\SharpRDP\bin\Release\AxInterop.MSTSCLib.dll") {
          [System.IO.Compression.DeflateStream]::CreateCompressor(".\SharpRDP\bin\Release\AxInterop.MSTSCLib.dll", ".\SharpRDP\bin\Release\AxInterop.MSTSCLib.dll.bin")
        }
        
        if (Test-Path ".\SharpRDP\bin\Release\Interop.MSTSCLib.dll") {
          [System.IO.Compression.DeflateStream]::CreateCompressor(".\SharpRDP\bin\Release\Interop.MSTSCLib.dll", ".\SharpRDP\bin\Release\Interop.MSTSCLib.dll.bin")
        }
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SharpRDP-Release
        path: |
          SharpRDP/bin/Release/SharpRDP.exe
          SharpRDP/bin/Release/*.dll.bin
